version: '3'
services:
  nginx:
    image: 'nginx:latest'
    ports:
      - '80:80'
    volumes:
      - './:/var/www'
      - './development/docker/vhost.conf:/etc/nginx/conf.d/default.conf'
    links:
      - php
  php:
    image: 'chialab/php-dev:7.2-fpm'
    volumes:
      - './:/var/www'
      - './development/docker/php/php-ini-overrides.ini:/usr/local/etc/php/conf.d/99-overrides.ini'
      - './development/docker/php/scripts:/scripts'
    restart: on-failure
    working_dir: /var/www/html
    depends_on:
      - db
  wpcli:
    image: 'chialab/php-dev:7.2-fpm'
    volumes:
      - './:/var/www'
      - './development/docker/php/scripts:/scripts'
      - './development/docker/php/php-ini-overrides.ini:/usr/local/etc/php/conf.d/99-overrides.ini'
    entrypoint:
      - bash
      - /scripts/entrypoint.sh
    working_dir: /var/www/html
    depends_on:
      - db
  db:
    image: 'mariadb:10.4'
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: t5_room_occupancy
      MYSQL_ROOT_PASSWORD: wp
    volumes:
      - 'db:/var/lib/mysql'
    healthcheck:
      test: '["CMD-SHELL", ''mysql --database=$$MYSQL_DATABASE --password=$$MYSQL_ROOT_PASSWORD --execute="SELECT count(table_name) > 0 FROM information_schema.tables;" --skip-column-names -B'']'
      interval: 30s
      timeout: 10s
      retries: 4
volumes:
  db: {  }
